import { UserProfile } from "@/types/profile";

export const dummyProfile: UserProfile = {
  id: "user-123",
  username: "gamerpro",
  displayName: "Alex Gaming",
  avatarUrl: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400",
  bannerUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=1920",
  bio: "Passionate gamer exploring epic adventures across all platforms. Always looking for co-op partners!",
  timezone: "CET",
  createdAt: "2024-01-15T10:00:00Z",
  stats: {
    gamesCount: 8,
    communitiesCount: 4,
    guidesCount: 3,
    eventsCount: 3,
  },
  favoriteGames: [
    {
      id: "game-1",
      title: "Red Dead Redemption 2",
      slug: "red-dead-redemption-2",
      coverUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=300",
      platforms: ["pc", "ps5"],
      status: "playing",
      hoursPlayed: 45,
    },
    {
      id: "game-2",
      title: "Elden Ring",
      slug: "elden-ring",
      coverUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=300",
      platforms: ["pc", "xbox"],
      status: "completed",
      hoursPlayed: 120,
    },
  ],
  games: [
    {
      id: "game-1",
      title: "Red Dead Redemption 2",
      slug: "red-dead-redemption-2",
      coverUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=300",
      platforms: ["pc", "ps5"],
      status: "playing",
      hoursPlayed: 45,
    },
    {
      id: "game-2",
      title: "Elden Ring",
      slug: "elden-ring",
      coverUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=300",
      platforms: ["pc", "xbox"],
      status: "completed",
      hoursPlayed: 120,
    },
    {
      id: "game-3",
      title: "Baldur's Gate 3",
      slug: "baldurs-gate-3",
      coverUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=300",
      platforms: ["pc"],
      status: "playing",
      hoursPlayed: 32,
    },
    {
      id: "game-4",
      title: "The Witcher 3",
      slug: "the-witcher-3",
      coverUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=300",
      platforms: ["pc", "ps5", "switch"],
      status: "completed",
      hoursPlayed: 95,
    },
    {
      id: "game-5",
      title: "Cyberpunk 2077",
      slug: "cyberpunk-2077",
      coverUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=300",
      platforms: ["pc", "ps5"],
      status: "wishlist",
    },
    {
      id: "game-6",
      title: "Hollow Knight",
      slug: "hollow-knight",
      coverUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=300",
      platforms: ["pc", "switch"],
      status: "added",
      hoursPlayed: 8,
    },
    {
      id: "game-7",
      title: "God of War",
      slug: "god-of-war",
      coverUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=300",
      platforms: ["ps5"],
      status: "playing",
      hoursPlayed: 12,
    },
    {
      id: "game-8",
      title: "Starfield",
      slug: "starfield",
      coverUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=300",
      platforms: ["pc", "xbox"],
      status: "wishlist",
    },
  ],
  communities: [
    {
      id: "comm-1",
      name: "RDR2 Posse",
      gameSlug: "red-dead-redemption-2",
      gameTitle: "Red Dead Redemption 2",
      membersCount: 1247,
      role: "mod",
      primaryPlatform: "discord",
      link: "https://discord.gg/example",
    },
    {
      id: "comm-2",
      name: "Elden Ring Co-op",
      gameSlug: "elden-ring",
      gameTitle: "Elden Ring",
      membersCount: 3421,
      role: "member",
      primaryPlatform: "discord",
      link: "https://discord.gg/example2",
    },
    {
      id: "comm-3",
      name: "Baldur's Gate LFG",
      gameSlug: "baldurs-gate-3",
      gameTitle: "Baldur's Gate 3",
      membersCount: 892,
      role: "owner",
      primaryPlatform: "discord",
      link: "https://discord.gg/example3",
    },
    {
      id: "comm-4",
      name: "Witcher Fans",
      gameSlug: "the-witcher-3",
      gameTitle: "The Witcher 3",
      membersCount: 2156,
      role: "member",
      primaryPlatform: "discord",
      link: "https://discord.gg/example4",
    },
  ],
  guides: [
    {
      id: "guide-1",
      title: "How to Play Cross-Platform: PC to PS5",
      gameSlug: "red-dead-redemption-2",
      gameTitle: "Red Dead Redemption 2",
      createdAt: "2024-12-01T14:30:00Z",
      upvotes: 42,
    },
    {
      id: "guide-2",
      title: "Best Build for New Players",
      gameSlug: "elden-ring",
      gameTitle: "Elden Ring",
      createdAt: "2024-11-25T10:15:00Z",
      upvotes: 89,
    },
    {
      id: "guide-3",
      title: "Co-op Setup Guide",
      gameSlug: "baldurs-gate-3",
      gameTitle: "Baldur's Gate 3",
      createdAt: "2024-11-20T16:45:00Z",
      upvotes: 156,
    },
  ],
  events: [
    {
      id: "event-1",
      title: "Looking for 2 players for PS2 co-op",
      gameTitle: "Red Dead Redemption 2",
      gameSlug: "red-dead-redemption-2",
      date: "2024-12-15T20:00:00Z",
      timeLabel: "Friday 20:00 CET",
      description: "Looking for experienced players to complete the heist missions. Mic required!",
      voicePlatform: "Discord",
      slotsTotal: 4,
      slotsTaken: 2,
      isPinned: true,
    },
    {
      id: "event-2",
      title: "Elden Ring Boss Run",
      gameTitle: "Elden Ring",
      gameSlug: "elden-ring",
      date: "2024-12-20T19:00:00Z",
      timeLabel: "Wednesday 19:00 CET",
      description: "Taking on Malenia and other endgame bosses. All skill levels welcome!",
      voicePlatform: "VC in-game",
      slotsTotal: 3,
      slotsTaken: 1,
      isPinned: false,
    },
    {
      id: "event-3",
      title: "Baldur's Gate 3 Campaign",
      gameTitle: "Baldur's Gate 3",
      gameSlug: "baldurs-gate-3",
      date: "2024-12-18T18:30:00Z",
      timeLabel: "Monday 18:30 CET",
      description: "Starting a fresh campaign. Looking for dedicated players for weekly sessions.",
      voicePlatform: "Discord",
      slotsTotal: 4,
      slotsTaken: 3,
      isPinned: false,
    },
  ],
};

